version: "3.4"

services:
  php:
    build:
      context: .
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - ./var/images:/srv/app/var/images
      - ./var/resized:/srv/app/var/resized
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-14}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      FTP_HOST: ${APP_FTP_HOST}
      FTP_LOGIN: ${APP_FTP_LOGIN}
      FTP_PASSWORD: ${APP_FTP_PASSWORD}
      FTP_PATH: ${APP_FTP_PATH}
      FTP_PATH_TEST: ${APP_FTP_PATH_TEST}
      FTP_PORT: ${APP_FTP_PORT:-21}

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

volumes:
  php_socket:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
